global:
  cluster:
    name:
    domain:

connector:
  host:
  entityID:
  metadataURL:

esp:
  replicaCount: 1
  image:
    repository: registry.tools.verify.govsvc.uk/eidas/parser
    tag: v0.0.0-dev-2626120
    pullPolicy: IfNotPresent

gateway:
  replicaCount: 1
  image:
    repository: registry.tools.verify.govsvc.uk/eidas/gateway
    tag: v0.0.0-dev-2626120
    pullPolicy: IfNotPresent
  errorPageURL: https://www.signin.service.gov.uk/proxy-node-error

hsm:
  IP:
  customerCA:
  user:
  password:
  image:
    repository: registry.tools.verify.govsvc.uk/eidas/cloudhsm
    tag: v0.0.0-dev-2626120
    pullPolicy: IfNotPresent

translator:
  replicaCount: 1
  image:
    repository: registry.tools.verify.govsvc.uk/eidas/translator
    tag: v0.0.0-dev-2626120
    pullPolicy: IfNotPresent

stubConnector:
  enabled: false
  replicaCount: 1
  image:
    repository: registry.tools.verify.govsvc.uk/eidas/stub-connector
    tag: v0.0.0-dev-2626120
    pullPolicy: IfNotPresent

vmc:
  image:
    repository: registry.tools.verify.govsvc.uk/eidas/metadata-controller
    tag: v0.0.0-dev-a23f39e
    pullPolicy: IfNotPresent
  secretName: test-vmc

vsp:
  replicaCount: 1
  image:
    repository: registry.tools.verify.govsvc.uk/eidas/verify-service-provider
    tag: v0.0.0-dev-d97a7c9
    pullPolicy: IfNotPresent
  secretName: test-vsp
