apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
      - {{ .Release.Name }}-gateway.{{ .Values.cluster.domain }}
      secretName: {{ .Release.Name }}-gateway
  rules:
    - host: {{ .Release.Name }}-gateway.{{ .Values.cluster.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-gateway
              servicePort: 6100
