apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: nginx-ingress
            release: ingress-system
        namespaceSelector:
          matchLabels:
            namespace: ingress-system
      ports:
      - protocol: TCP
        port: 80
