apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-metadata
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Release.Name }}-metadata
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
      - {{ include "metadata.host" . }}
      secretName: {{ .Release.Name }}-metadata-ingress
  rules:
    - host: {{ include "metadata.host" . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-proxy-metadata
              servicePort: 80
