apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: stub-connector-metadata-network-policy
spec:
  podSelector:
    matchLabels:
      deployment: {{ .Release.Name }}-connector-metadata-deployment
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: esp
            app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
      - protocol: TCP
        port: 80
