apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-stub-connector-pki
type: Opaque
data:
  CONNECTOR_NODE_BASE_URL: PLACEHOLDER
  ENCRYPTION_CERT: PLACEHOLDER
  ENCRYPTION_KEY: PLACEHOLDER
  PROXY_NODE_ENTITY_ID: PLACEHOLDER
  PROXY_NODE_METADATA_TRUSTSTORE: PLACEHOLDER
  PROXY_NODE_METADATA_TRUSTSTORE_PASSWORD: PLACEHOLDER
  SIGNING_CERT: PLACEHOLDER
  SIGNING_KEY: PLACEHOLDER
