{{- if .Values.stubConnector.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: stub-connector-network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: connector
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            istio: ingressgateway
        namespaceSelector:
          matchLabels:
            namespace: istio-system
      ports:
      - protocol: TCP
        port: 80
{{- end -}}
